version: "3.8"

services:
  server:
    build: ./server
    volumes:
      - ./server/uploads:/app/uploads
    command: ["npm", "start"]
    ports:
      - "8000:8000"
    environment:
      - HF_API_KEY=${HF_API_KEY}
      - PORT=${PORT}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}

  worker:
    build: ./server
    volumes:
      - ./server/uploads:/app/uploads
    command: ["npm", "run", "worker"]
    environment:
      - HF_API_KEY=${HF_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - server
