# version: "3.8"

# services:
#   valkey:
#     image: valkey/valkey
#     ports:
#       - 6379:6379

#   qdrant:
#     image: qdrant/qdrant
#     ports:
#       - 6333:6333

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - HF_API_KEY=${HF_API_KEY}   # variabilele se pun în .env
      - PORT=8000
      - GROQ_API_KEY=${GROQ_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
    volumes:
      - ./server:/app
    depends_on:
      - redis
      - qdrant

# Worker pentru procesarea joburilor
  worker:
    build: ./server
    command: npm run dev:worker
    environment:
      - HF_API_KEY=${HF_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./server:/app
    depends_on:
      - redis
      - qdrant

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./client:/app
    depends_on:
      - server

  redis:
    image: redis:7
    ports: 
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  qdrant_storage:
